# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/14315/Desktop/vivado/第二次实验/icf.xdc

# IP: ip/imem/imem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==imem || ORIG_REF_NAME==imem} -quiet] -quiet
